# [deploy-r16] source me: the R16 flag sets (the ship configuration of docs/DEPLOY_R16.md).
# R16_ON_ENV / R16_R15_ENV use tests/gpu_run.sh's GPU_RUN_ENV syntax (NAME=value;...).
# Every R16 runtime knob of the bundle (the launcher forwards all of them to both ranks; empty = the module default):
R16_KNOBS="GLM53_PREFILL_QUICKWINS GLM53_PREFILL_QUICKWINS_MIN_T
GLM53_MLA_PREFILL GLM53_MLA_PREFILL_MIN_TOKENS GLM53_MLA_PREFILL_MIXED GLM53_MLA_PREFILL_VARIANT
GLM53_DEC_FP8ROOF GLM53_DEC_FP8ROOF_TABLE GLM53_DEC_FP8ROOF_PF GLM53_DEC_FP8ROOF_PF_MIB GLM53_DEC_FP8ROOF_PF_CTAS
GLM53_DEC_FP8ROOF_PF_POL GLM53_DEC_FP8ROOF_PF_MAX_M
GLM53_DEC_MOEGLUE GLM53_DEC_MOEGLUE_PREFETCH GLM53_DEC_MOEGLUE_WARM GLM53_DEC_MOEGLUE_WARM_SET GLM53_DEC_MOEGLUE_WARM_MIB
GLM53_DEC_MOEGLUE_WARM_BLOCKS GLM53_DEC_MOEGLUE_WARM_MAX_M
GLM53_DEC_HOSTLOOP GLM53_DEC_HOSTLOOP_VERIFY GLM53_DEC_HOSTLOOP_VERIFY_EVERY GLM53_DEC_HOSTLOOP_METER
GLM53_DEC_HOSTLOOP_WAKE GLM53_DEC_HOSTLOOP_WAKE_TICK_US GLM53_DEC_HOSTLOOP_WAKE_PIN GLM53_DEC_PROF_DIAG
GLM53_DEC_SMALLOPS GLM53_DEC_SMALLOPS_KINDS GLM53_DEC_KDA_LAZY GLM53_DEC_KDA_LAZY_VERIFY GLM53_DEC_KDA_LAZY_VERIFY_EVERY GLM53_DEC_VTRIM_STATS GLM53_DEC_VTRIM_STATS_CAP GLM53_DEC_VTRIM_STATS_FILE
GLM53_KPOOL_RING"
# the ship values (everything else stays unset = off / default): bit-identical prefill quick wins, exact sparse-MLA
# prefill kernel, decode L2 prefetch + drafter fc table, MoE-sublayer L2 warm, host-loop planner, DFlash2 grouped conv
# kernel only (no mHC bf16 copies: 0 MiB), kpool tail ring
R16_ON_ENV="GLM53_PREFILL_QUICKWINS=all;GLM53_MLA_PREFILL=1;GLM53_DEC_FP8ROOF=1;GLM53_DEC_MOEGLUE_WARM=1;GLM53_DEC_HOSTLOOP=1;GLM53_DEC_SMALLOPS=1;GLM53_DEC_SMALLOPS_KINDS=dconv;GLM53_KPOOL_RING=1"
# production's R15 plugin env (nodeA .env, env_nonsecret.txt 2026-09-28): what the bundle sees today
R16_R15_ENV="TF_EXL3_MOE=1;GLM53_PREFILL_FUSED_CAP=1;GLM53_MEM_HYGIENE=1;GLM53_TF_PROFILE=/tmp/glm53-prof;GLM53_LMHEAD_FP8=1;GLM53_FP8_GEMV=1;GLM53_FP8_GEMV_MAX_M=16;GLM53_BF16_GEMV=1;GLM53_BF16_GEMV_DEDUP_ROUTER=1;GLM53_FP8_LARGE_M=1;GLM53_KPOOL_SEED_STRIDE=1;GLM53_SPEC_RESAMPLE_INDEPENDENT=1;GLM53_DRAFT_FP8=layers,fc"
# launcher (APC short-suffix fix, ${TF_EXL3_KITS:-$HOME}/tf-exl3-launcher-apc main): .env additions
R16_LAUNCHER_ENV="GLM53_DRAFT_KV_COMPACT=1;GLM53_APC_DRAFTER_LOW_PRIORITY=0"
